type t =
  | DedicationChurch
  | BlessedVirginMary
  | BlessedVirginMaryOptionalMemorial
  | Apostles
  | SeveralMartyrs
  | SeveralVirginMartyrs
  | SeveralHolyWomenMartyrs
  | OneMartyr
  | OneVirginMartyr
  | OneHolyWomanMartyr
  | PopePastor
  | BishopPastor
  | FounderOfChurchPaster
  | Pastor
  | MissionaryPastor
  | ChurchDoctor
  | Virgin
  | VirginMartyr
  | SeveralVirgins
  | HolyMen
  | SeveralHolyMen
  | HolyMenReligious
  | HolyMenUnderprivildged
  | HolyMenTeacher
  | HolyMenMarried
  | HolyWomen
  | SeveralHolyWomen
  | HolyWomenReligious
  | HolyWomenUnderprivildged
  | HolyWomenTeacher
  | HolyWomenMarried
  | ReligiousMan
  | ReligiousWomen
  | ReligiousAbbot
  | TeacherMan
  | TeacherWoman
  | Underprivilidged
